/**
 * CraftPix RPG Magic Icons & Spellbook Pixel UI Pack (product 172265).
 *
 * Disk SSOT: D:\Games\Models\craftpix-rpg-magic-spellbook-ui
 * App path:  public/ui/craftpix/spellbook/**
 * Catalog:   public/ui/craftpix/spellbook/catalog.json  (generated by stage-spellbook-pack.mjs)
 *
 * Author layout:
 *   Icons.png 576×320 → 32×32 cells (18×10), upscaled to 96px for UI
 *   sells_full.png → skill slot frames under slots/
 *   book_page / book_content / gems / panels chrome
 *
 * Do not invent parallel spell-icon folders; re-run the stage script.
 */

import catalogJson from "./spellbookCatalog.json";

const BASE = (import.meta.env.BASE_URL ?? "/").replace(/\/$/, "");

export type SpellSchoolId = "fire" | "air" | "water" | "earth";

export interface SpellbookIcon {
  id: string;
  school: SpellSchoolId;
  name: string;
  label: string;
  file: string;
  tile?: { col: number; row: number; size: number };
  index?: number;
}

export interface SpellSchool {
  id: SpellSchoolId;
  label: string;
  accent: string;
  iconCount: number;
  gem?: string | null;
}

export interface SpellbookSlot {
  id: string;
  file: string;
  role?: string;
  col?: number;
  row?: number;
}

export interface FirstBookDef {
  id: string;
  school: SpellSchoolId;
  title: string;
  blurb: string;
  unlockSkillIds: string[];
}

const catalog = catalogJson as {
  pack: string;
  version?: number;
  schools: SpellSchool[];
  chrome: Record<string, string>;
  icons: SpellbookIcon[];
  slots?: SpellbookSlot[];
  gems?: Array<{ id: string; file: string; school: string }>;
  firstBooks: FirstBookDef[];
  iconCellSize?: number;
  iconDisplaySize?: number;
};

export const SPELLBOOK_PACK_ID = catalog.pack;
export const SPELLBOOK_VERSION = catalog.version ?? 1;
export const SPELLBOOK_SCHOOLS: SpellSchool[] = catalog.schools;
export const SPELLBOOK_ICONS: SpellbookIcon[] = catalog.icons;
export const SPELLBOOK_SLOTS: SpellbookSlot[] = catalog.slots ?? [];
export const FIRST_SKILL_BOOKS: FirstBookDef[] = catalog.firstBooks;

const ICON_BY_ID = new Map(SPELLBOOK_ICONS.map((i) => [i.id, i]));
const ICONS_BY_SCHOOL = new Map<SpellSchoolId, SpellbookIcon[]>();
for (const icon of SPELLBOOK_ICONS) {
  const list = ICONS_BY_SCHOOL.get(icon.school) ?? [];
  list.push(icon);
  ICONS_BY_SCHOOL.set(icon.school, list);
}

/** Public URL under Vite BASE for a catalog-relative file. */
export function spellbookUrl(rel: string): string {
  const path = rel.replace(/^\//, "");
  return `${BASE}/ui/craftpix/spellbook/${path}`;
}

export function spellbookChromeUrl(key: string): string {
  const file = catalog.chrome[key] ?? catalog.chrome.bookPage ?? "book_page.png";
  return spellbookUrl(file);
}

export function spellbookIconUrl(iconId: string): string | null {
  const icon = ICON_BY_ID.get(iconId);
  return icon ? spellbookUrl(icon.file) : null;
}

/** Skill slot frame (default mid ornate plate from sells_full). */
export function spellbookSlotUrl(slotId = "slot_default"): string {
  const slot =
    SPELLBOOK_SLOTS.find((s) => s.id === slotId) ??
    SPELLBOOK_SLOTS.find((s) => s.id === "slot_default") ??
    SPELLBOOK_SLOTS[0];
  if (slot) return spellbookUrl(slot.file);
  return spellbookChromeUrl("slotDefault") || spellbookChromeUrl("slotTileset");
}

export function spellbookGemUrl(school: SpellSchoolId): string | null {
  const g = catalog.gems?.find((x) => x.school === school);
  if (g) return spellbookUrl(g.file);
  const key = `gem_${school}`;
  if (catalog.chrome[key]) return spellbookUrl(catalog.chrome[key]);
  return null;
}

export function iconsForSchool(school: SpellSchoolId): SpellbookIcon[] {
  return ICONS_BY_SCHOOL.get(school) ?? [];
}

export function schoolById(id: string): SpellSchool | undefined {
  return SPELLBOOK_SCHOOLS.find((s) => s.id === id);
}

/**
 * Map combat element / skill keywords → elemental school for first-book icons.
 */
export function schoolForElement(element?: string | null): SpellSchoolId {
  const e = (element ?? "").toLowerCase();
  if (/fire|flame|ember|meteor|burn|lava|hiken/.test(e)) return "fire";
  if (/water|ice|frost|cold|chill|snow|freeze|bubble/.test(e)) return "water";
  if (/earth|stone|rock|nature|leaf|vine|poison|grass|golem/.test(e)) return "earth";
  if (/air|wind|lightning|storm|thunder|shock|arcane|psychic|electric/.test(e)) return "air";
  if (/physical|slash|melee|blade|sword/.test(e)) return "fire";
  return "air";
}

/** Pick a stable spellbook icon for a skill by id/name/element. */
export function pickSpellbookIconForSkill(opts: {
  skillId?: string;
  skillName?: string;
  element?: string;
}): SpellbookIcon | null {
  const school = schoolForElement(opts.element ?? opts.skillName ?? opts.skillId);
  const pool = iconsForSchool(school);
  if (!pool.length) return null;
  const blob = `${opts.skillId ?? ""} ${opts.skillName ?? ""}`.toLowerCase();
  for (const icon of pool) {
    const n = icon.name.replace(/_/g, " ");
    if (blob.includes(n) || blob.includes(icon.name.replace(/_/g, ""))) return icon;
  }
  const keys: Array<[RegExp, string]> = [
    [/fireball|meteor/, "fireball"],
    [/shield|ward|block/, "shield"],
    [/arrow|bolt/, "arrow"],
    [/storm|whirl|wave/, "storm"],
    [/fist|punch|slam/, "fist"],
    [/blade|slash|sword/, "blade"],
    [/drop|bubble/, "drop"],
    [/leaf|vine|tree/, "leaf"],
  ];
  for (const [re, key] of keys) {
    if (!re.test(blob)) continue;
    const hit = pool.find((i) => i.name.includes(key));
    if (hit) return hit;
  }
  let h = 0;
  for (let i = 0; i < blob.length; i++) h = (h * 31 + blob.charCodeAt(i)) >>> 0;
  return pool[h % pool.length] ?? pool[0]!;
}
